// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8M37xc-aMGVNrhPw0X5-bIgwejpQS-U',
    appId: '1:428055034017:web:d4e805b47851aeb30818e0',
    messagingSenderId: '428055034017',
    projectId: 'chatapplication-1d161',
    authDomain: 'chatapplication-1d161.firebaseapp.com',
    storageBucket: 'chatapplication-1d161.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS58p5SAIiYveYL2TUELeSOcwzAhAChsU',
    appId: '1:428055034017:android:bbd9507b3d6567c50818e0',
    messagingSenderId: '428055034017',
    projectId: 'chatapplication-1d161',
    storageBucket: 'chatapplication-1d161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3pg1dbCW2sIcSehefIh-S8N9Z9xa9B28',
    appId: '1:428055034017:ios:d3856df85315b3a80818e0',
    messagingSenderId: '428055034017',
    projectId: 'chatapplication-1d161',
    storageBucket: 'chatapplication-1d161.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3pg1dbCW2sIcSehefIh-S8N9Z9xa9B28',
    appId: '1:428055034017:ios:d3856df85315b3a80818e0',
    messagingSenderId: '428055034017',
    projectId: 'chatapplication-1d161',
    storageBucket: 'chatapplication-1d161.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV8M37xc-aMGVNrhPw0X5-bIgwejpQS-U',
    appId: '1:428055034017:web:9e14eac1074f5d070818e0',
    messagingSenderId: '428055034017',
    projectId: 'chatapplication-1d161',
    authDomain: 'chatapplication-1d161.firebaseapp.com',
    storageBucket: 'chatapplication-1d161.firebasestorage.app',
  );
}
